# Generated by Django 3.2.16 on 2023-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_auto_20181005_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="type",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                    ("main", "Main"),
                    ("cell", "Cellular"),
                    ("fax", "Fax"),
                    ("pager", "Pager"),
                ],
                max_length=20,
            ),
        ),
    ]
