# Generated by Django 4.2.5 on 2023-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_phonenumber_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
