# Generated by Django 5.2.9 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_alter_contact_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="syncing",
            field=models.BooleanField(default=False),
        ),
    ]
