comment:
  layout: header, changes, diff
coverage:
  ignore:
  - **/migrations/*
  - **/tests/*
  - **/tests.py
  - modoboa/core/dev_settings.py
  - modoboa/test_settings.py
  status:
    patch:
      default:
        target: '70'
    project:
      default:
        target: auto
