comment:
  layout: header, changes, diff
coverage:
  ignore:
  - modoboa/core/migrations/*
  - modoboa/core/tests.py
  - modoboa/core/dev_settings.py
  - modoboa/lib/migrations/*
  - modoboa/lib/tests.py
  - modoboa/admin/migrations/*
  - modoboa/admin/tests/*
  - modoboa/limits/migrations/*
  - modoboa/limits/tests.py
  - modoboa/relaydomains/migrations/*
  - modoboa/relaydomains/tests.py
  status:
    patch:
      default:
        target: '70'
    project:
      default:
        target: auto
