FROM python:3.6-alpine as base

MAINTAINER Antoine Nguyen <tonio@ngyn.org>

RUN apk add --update openssl librrd python3-dev libffi-dev gcc musl-dev libxml2-dev libxslt-dev \
    libressl-dev jpeg-dev rrdtool-dev file make \
    && rm -rf /var/cache/apk/*

WORKDIR /tmp
COPY requirements.txt /tmp
COPY test-requirements.txt /tmp
RUN pip install --user  -r requirements.txt --user -r test-requirements.txt

FROM python:3.6-alpine
COPY --from=base /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH
RUN apk add --no-cache --update libxml2-dev libxslt-dev\
    && rm -rf /var/cache/apk/*

RUN mkdir /code
WORKDIR /code
