# Generated by Django 4.2 on 2023-04-25 12:00

from django.db import migrations

# Due to a bug, this migration has been changed...


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_user_language"),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name="user",
        #     new_name="core_user_email_c0c03f_idx",
        #     old_fields=("email", "is_active"),
        # ),
    ]
