# Generated by Django 4.2.6 on 2023-10-24 17:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_user_email_is_active_core_user_email_c0c03f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localconfig",
            name="_parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="localconfig",
            name="api_versions",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="_parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="localconfig",
            name="api_versions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="localconfig",
            name="_parameters",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="localconfig",
            name="api_versions",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="_parameters",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
