# Generated by Django 4.2.11 on 2024-03-20 11:11

from django.db import migrations, models
import modoboa.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_localconfig__parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("br", "breton"),
                    ("cs", "čeština"),
                    ("de", "deutsch"),
                    ("en", "english"),
                    ("el", "ελληνικά"),
                    ("es", "español"),
                    ("fi", "Suomalainen"),
                    ("fr", "français"),
                    ("it", "italiano"),
                    ("ja", "日本の"),
                    ("nl", "nederlands"),
                    ("pt", "português"),
                    ("pt-br", "português (BR)"),
                    ("pl", "polski"),
                    ("ro", "Română"),
                    ("ru", "русский"),
                    ("sv", "svenska"),
                    ("tr", "türk"),
                    ("zh-hant", "中文（台灣）"),
                ],
                default=modoboa.core.models.get_default_language,
                help_text="Prefered language to display pages.",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
