# Generated by Django 5.2.4 on 2025-07-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_rename_tfa_enabled_user_totp_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
