# Generated by Django 5.2.17 on 2026-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0031_normalize_legacy_language_codes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="objectaccess",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="core_object_content_6b9cf4_idx",
            ),
        ),
    ]
