"""Management command to handle file generation."""

import datetime
import io

from django.core.management.base import BaseCommand

from modoboa.admin.models import Domain
from modoboa.core.models import User
from modoboa.parameters import tools as param_tools

from ... import models

HEADER = """# Rights management file for Radicale
# This file was generated by Modoboa on {date}
# DO NOT EDIT MANUALLY!
"""


class Command(BaseCommand):
    """Management command to handle file generation."""

    help = "Generate Radicale rights file"

    def add_arguments(self, parser):
        """Add extra arguments to command line."""
        parser.add_argument(
            "--force",
            action="store_true",
            default=False,
            help="Force generation of rights file",
        )

    def _generate_acr(self, name, user, collection, perm="RrWw", comment=None):
        """Write a new access control rule to the config file."""
        if comment is not None:
            self._cfgfile.write(f"\n# {comment}")
        self._cfgfile.write(
            f"""
[{name}]
user: {user}
collection: {collection}
permissions: {perm}
"""
        )

    def _user_access_rules(self):
        """Create user access rules."""
        qset = models.AccessRule.objects.order_by("pk").values_list(
            "mailbox__address",
            "mailbox__domain__name",
            "calendar__name",
            "calendar___path",
            "read",
            "write",
        )
        for address, domain, name, path, read, write in qset.iterator():
            email = f"{address}@{domain}"
            permission = ""
            if read:
                permission += "Rr"
            if write:
                permission += "Ww"
            self._generate_acr(f"{email}-to-{name}-acr", email, path, permission)

    def _token_access_rules(self):
        """Create token access rules."""
        for model in [models.UserCalendar, models.SharedCalendar]:
            qset = model.objects.order_by("pk").values_list("_path", "access_token")
            for path, token in qset.iterator():
                self._generate_acr(
                    f"token-{path}-access",
                    token,
                    path,
                    perm="Rr",
                    comment="Read-only access using a token",
                )

    def _super_admin_rules(self):
        """Generate access rules for super administrators."""
        qset = (
            User.objects.filter(is_superuser=True)
            .order_by("pk")
            .values_list("username", flat=True)
        )
        for username in qset.iterator():
            self._generate_acr(f"sa-{username}-acr", username, ".*")

    def _domain_admin_rules(self):
        """Generate access rules for domain adminstrators."""
        for da in User.objects.filter(groups__name="DomainAdmins").order_by("pk"):
            domains = (
                Domain.objects.get_for_admin(da)
                .order_by("pk")
                .values_list("name", flat=True)
            )
            for domain in domains:
                section = f"da-{da.email}-to-{domain}-acr"
                self._generate_acr(section, da.email, f"{domain}/user/.*")

    def _generate_rules(self):
        """Return the rules part of the file (everything but the header).

        A user must not declare a rule for his direct admin!
        """
        self._cfgfile = io.StringIO()
        allow_calendars_administration = param_tools.get_global_parameter(
            "allow_calendars_administration", app="calendars"
        )
        if allow_calendars_administration:
            self._super_admin_rules()
            self._domain_admin_rules()

        # self._generate_acr(
        #     "domain-shared-calendars", r"^(.+)@(.+)$", r"{1}/.+$",
        #     comment="Access rule to domain shared calendars"
        # )
        self._generate_acr(
            "principal",
            r".+",
            r"{user}",
            perm="RW",
            comment="Allow reading and writing principal collection "
            "(same as user name)",
        )
        self._generate_acr(
            "calendars",
            r".+",
            r"{user}/[^/]+",
            comment="Allow reading and writing calendars and address books "
            "that are direct children of the principal collection",
        )

        self._user_access_rules()
        self._token_access_rules()
        return self._cfgfile.getvalue()

    def _read_current_rules(self, path):
        """Return the rules part of the current file, None if unreadable."""
        header_lines = HEADER.count("\n")
        try:
            with open(path) as fp:
                content = fp.read()
        except OSError:
            return None
        parts = content.split("\n", header_lines)
        if len(parts) <= header_lines:
            return None
        return parts[header_lines]

    def handle(self, *args, **options):
        """Command entry point.

        The file is rewritten only when its rules changed. Comparing
        content (and not modification dates) also catches deletions:
        removed access rules, calendars, accounts or administrators.
        """
        path = param_tools.get_global_parameter("rights_file_path", app="calendars")
        rules = self._generate_rules()
        if not options["force"] and rules == self._read_current_rules(path):
            return
        with open(path, "w") as fp:
            fp.write(HEADER.format(date=datetime.datetime.today()) + rules)
