# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imap_migration", "0003_auto_20190207_0919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migration",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="imap_migration.EmailProvider",
            ),
        ),
        migrations.AlterField(
            model_name="migration",
            name="username",
            field=models.CharField(max_length=254),
        ),
    ]
