# Generated by Django 2.2.12 on 2021-04-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imap_migration", "0004_auto_20190207_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailproviderdomain",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="imap_migration.EmailProvider",
            ),
        ),
        migrations.AlterField(
            model_name="migration",
            name="username",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
