# Generated by Django 5.2.10 on 2026-02-02 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("to", models.TextField()),
                ("cc", models.TextField(blank=True, null=True)),
                ("bcc", models.TextField(blank=True, null=True)),
                (
                    "in_reply_to",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("scheduled_datetime", models.DateTimeField()),
                ("imap_uid", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("sending", "sending"),
                            ("send_error", "send_error"),
                            ("move_error", "move_error"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("content_type", models.CharField(max_length=150)),
                ("filename", models.CharField(max_length=255)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="webmail.scheduledmessage",
                    ),
                ),
            ],
        ),
    ]
