# Generated by Django 5.2.17 on 2026-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webmail", "0005_scheduledmessage_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
