# Generated by Django 4.2.6 on 2023-10-24 17:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_auto_20180928_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="transport",
            name="_settings",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
