# Generated by Django 4.2.22 on 2025-06-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autoreply", "0011_auto_20250609_0851"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ARhistoric",
        ),
    ]
