# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relaydomains', '0002_migrate_from_modoboa_admin_relaydomains'),
        ('admin', '0006_auto_20161104_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaydomain',
            name='dates',
        ),
    ]
