# Generated by Django 3.2.12 on 2022-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaydomains', '0009_auto_20171124_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
