# Generated by Django 5.2.14 on 2026-06-30 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0005_auto_20200220_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedcalendar",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Calendar name contains invalid characters.",
                        regex="^[^/\\\\\\r\\n\\x00]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usercalendar",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Calendar name contains invalid characters.",
                        regex="^[^/\\\\\\r\\n\\x00]+$",
                    )
                ],
            ),
        ),
    ]
