# Generated by Django 5.2.17 on 2026-09-25 14:18

import modoboa.calendars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0006_alter_sharedcalendar_name_alter_usercalendar_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedcalendar",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[modoboa.calendars.models.calendar_name_validator],
            ),
        ),
        migrations.AlterField(
            model_name="usercalendar",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[modoboa.calendars.models.calendar_name_validator],
            ),
        ),
    ]
