# Generated by Django 5.2.17 on 2026-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0024_domain_last_dns_check_execution"),
        ("calendars", "0008_rename_duplicate_calendars"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sharedcalendar",
            constraint=models.UniqueConstraint(
                fields=("domain", "name"), name="radicale_sharedcalendar_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercalendar",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "name"), name="radicale_usercalendar_unique_name"
            ),
        ),
    ]
