# Generated by Django 5.2.17 on 2026-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0009_calendar_name_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrule",
            name="color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
