# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postfix_autoreply", "0007_auto_20180928_1423"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transport",
        ),
    ]
