#!/bin/sh

PYTHON=python
BASEDIR=/var/www
# If the user executing this script has no homedir or no shell, you
# must need to set the above variable.
EGG_CACHE=""

PYTHON_EGG_CACHE=$EGG_CACHE PYTHONPATH=$BASEDIR \
    DJANGO_SETTINGS_MODULE=modoboa.settings $PYTHON \
    $BASEDIR/modoboa/scripts/postfix_autoreply/autoreply.py $1 $2
