#!/bin/sh

BASEDIR=/home/tonio/projets/devel
export PYTHONPATH=$BASEDIR
export DJANGO_SETTINGS_MODULE=mailng.settings
#export PYTHON_EGG_CACHE=/tmp

$BASEDIR/mailng/scripts/postfix_autoreply/autoreply.py $1 $2
