# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20151118_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSBLResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=254, db_index=True)),
                ('mx', models.GenericIPAddressField()),
                ('status', models.CharField(blank=True, max_length=45, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Domain')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dnsblresult',
            unique_together=set([('domain', 'provider', 'mx')]),
        ),
    ]
