# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20160608_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alias',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
