# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20160719_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Mailbox')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='senderaddress',
            unique_together=set([('address', 'mailbox')]),
        ),
    ]
