# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20160910_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MXRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.GenericIPAddressField()),
                ('managed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Domain')),
            ],
        ),
    ]
