# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_mxrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsblresult',
            name='mx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.MXRecord'),
        ),
    ]
