# Generated by Django 2.2.10 on 2020-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_rename_view_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedDovecotUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
