# Generated by Django 4.2.1 on 2023-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0020_auto_20210130_2226"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="is_send_only",
            field=models.BooleanField(default=False),
        ),
    ]
