# Generated by Django 4.2.9 on 2024-02-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0021_mailbox_is_send_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="admin.domain",
            ),
        ),
    ]
