# Generated by Django 5.2.11 on 2026-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0023_auto_20240320_1037"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="last_dns_check_execution",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
